<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { addCustomerServiceTicketMessage, getCustomerServiceTicket, listCustomerServiceTickets, updateCustomerServiceTicketStatus } from '@/api/stageFortyOne'
import type { CustomerServiceTicket, CustomerServiceTicketDetail } from '@/types/stageFortyOne'
const tickets=ref<CustomerServiceTicket[]>([]);const selected=ref<CustomerServiceTicketDetail|null>(null);const error=ref('');const reply=ref('');const loading=ref(false)
async function load(){const r=await listCustomerServiceTickets({size:50});if(r.code===0)tickets.value=r.data.records;else error.value=r.message}
async function open(t:CustomerServiceTicket){const r=await getCustomerServiceTicket(t.ticketId);if(r.code===0)selected.value=r.data}
async function change(status:string){if(!selected.value)return;const r=await updateCustomerServiceTicketStatus(selected.value.ticket.ticketId,status,status==='RESOLVED'?'已处理完成':'');if(r.code===0){await load();await open(r.data)}else error.value=r.message}
async function send(){if(!selected.value||!reply.value.trim())return;loading.value=true;const r=await addCustomerServiceTicketMessage(selected.value.ticket.ticketId,reply.value.trim());if(r.code===0){reply.value='';await open(selected.value.ticket)}else error.value=r.message;loading.value=false}
onMounted(load)
</script>
<template><view class="cs-panel"><view class="heading">客服工单</view><view v-if="error" class="error">{{error}}</view><view class="layout"><view class="list"><view v-for="ticket in tickets" :key="ticket.ticketId" class="row" @click="open(ticket)"><strong>{{ticket.elderName}}</strong><text>{{ticket.category}} · {{ticket.priority}} · {{ticket.ticketStatus}}</text><small>{{ticket.description}}</small></view><view v-if="!tickets.length">暂无客服工单</view></view><view v-if="selected" class="detail"><strong>{{selected.ticket.elderName}}的协助请求</strong><p>{{selected.ticket.description}}</p><view v-for="m in selected.messages" :key="m.messageId" class="message"><b>{{m.senderRole}}</b> {{m.content}}</view><view class="actions"><button v-if="selected.ticket.ticketStatus==='PENDING'" @click="change('PROCESSING')">开始处理</button><button v-if="selected.ticket.ticketStatus==='PROCESSING'" @click="change('RESOLVED')">解决</button><button v-if="selected.ticket.ticketStatus==='PENDING'||selected.ticket.ticketStatus==='PROCESSING'" @click="change('CLOSED')">关闭</button></view><textarea v-model="reply" placeholder="回复用户"/><button :disabled="loading" @click="send">发送回复</button></view></view></view></template>
<style scoped>.cs-panel{padding:24px;background:#fff}.heading{font-size:22px;font-weight:700;margin-bottom:18px}.layout{display:grid;grid-template-columns:minmax(240px,1fr) minmax(300px,1.5fr);gap:18px}.row,.detail{padding:16px;border:1px solid #dce7e4;border-radius:8px;margin-bottom:10px}.row{display:grid;gap:7px;cursor:pointer}.row small{color:#667}.message{padding:10px 0;border-bottom:1px solid #eee}.actions{display:flex;gap:8px;margin:14px 0}.error{color:#a43d31;margin:10px 0}textarea{width:100%;min-height:80px;box-sizing:border-box;margin:10px 0}@media(max-width:700px){.layout{grid-template-columns:1fr}}</style>
