DROP TABLE IF EXISTS operation_log;
DROP TABLE IF EXISTS service_report_item;
DROP TABLE IF EXISTS service_report;
DROP TABLE IF EXISTS medical_file;
DROP TABLE IF EXISTS file_asset;
DROP TABLE IF EXISTS nurse_task;
DROP TABLE IF EXISTS nursing_order;
DROP TABLE IF EXISTS service_item;
DROP TABLE IF EXISTS care_plan;
DROP TABLE IF EXISTS risk_tag;
DROP TABLE IF EXISTS allergy_record;
DROP TABLE IF EXISTS medication_plan;
DROP TABLE IF EXISTS chronic_disease;
DROP TABLE IF EXISTS health_archive;
DROP TABLE IF EXISTS elder_profile;

CREATE TABLE elder_profile(elder_id VARCHAR(32) PRIMARY KEY,user_id VARCHAR(32),elder_name VARCHAR(64),gender VARCHAR(16),birth_date DATE,care_level VARCHAR(32));
CREATE TABLE health_archive(archive_id VARCHAR(32) PRIMARY KEY,elder_id VARCHAR(32),archive_version INT,care_summary VARCHAR(512));
CREATE TABLE chronic_disease(disease_id VARCHAR(32) PRIMARY KEY,elder_id VARCHAR(32),disease_name VARCHAR(64),disease_status VARCHAR(32),diagnosed_at DATE,remark VARCHAR(255));
CREATE TABLE medication_plan(medication_id VARCHAR(32) PRIMARY KEY,elder_id VARCHAR(32),medication_name VARCHAR(64),dosage VARCHAR(64),frequency VARCHAR(64),time_points VARCHAR(1000),start_date DATE,end_date DATE,medication_status VARCHAR(32),remark VARCHAR(255));
CREATE TABLE allergy_record(allergy_id VARCHAR(32) PRIMARY KEY,elder_id VARCHAR(32),allergen VARCHAR(64),reaction VARCHAR(128),severity VARCHAR(32),remark VARCHAR(255));
CREATE TABLE risk_tag(risk_tag_id VARCHAR(32) PRIMARY KEY,elder_id VARCHAR(32),tag_code VARCHAR(64),tag_name VARCHAR(64),risk_level VARCHAR(32),remark VARCHAR(255));
CREATE TABLE care_plan(care_plan_id VARCHAR(32) PRIMARY KEY,elder_id VARCHAR(32),plan_content VARCHAR(4000),plan_status VARCHAR(32));
CREATE TABLE service_item(service_id VARCHAR(32) PRIMARY KEY,service_name VARCHAR(128));
CREATE TABLE nursing_order(order_id VARCHAR(32) PRIMARY KEY,elder_id VARCHAR(32),service_id VARCHAR(32),order_status VARCHAR(32),scheduled_start_at TIMESTAMP);
CREATE TABLE nurse_task(task_id VARCHAR(32) PRIMARY KEY,order_id VARCHAR(32),nurse_id VARCHAR(32),task_status VARCHAR(32));
CREATE TABLE file_asset(file_id VARCHAR(32) PRIMARY KEY,original_name VARCHAR(255),mime_type VARCHAR(128),file_size BIGINT,storage_bucket VARCHAR(64),object_key VARCHAR(255),audit_status VARCHAR(32));
CREATE TABLE medical_file(medical_file_id VARCHAR(32) PRIMARY KEY,elder_id VARCHAR(32),file_id VARCHAR(32),file_type VARCHAR(32),title VARCHAR(128),occurred_at DATE,audit_status VARCHAR(32),review_comment VARCHAR(255));
CREATE TABLE service_report(report_id VARCHAR(32) PRIMARY KEY,order_id VARCHAR(32),report_status VARCHAR(32),summary VARCHAR(1000),nursing_advice VARCHAR(1000),generated_at TIMESTAMP);
CREATE TABLE service_report_item(item_id VARCHAR(32) PRIMARY KEY,report_id VARCHAR(32),item_type VARCHAR(32),item_title VARCHAR(128),item_content VARCHAR(1000),sort INT);
CREATE TABLE operation_log(log_id VARCHAR(32) PRIMARY KEY,operator_id VARCHAR(32),role_code VARCHAR(64),operation_type VARCHAR(64),biz_type VARCHAR(64),biz_id VARCHAR(64),before_value VARCHAR(4000),after_value VARCHAR(4000),trace_id VARCHAR(64),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
