package com.csu.carenest.careadmin.customer;
import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Repository; import java.util.*;
@Repository public class CustomerServiceTicketRepository {
 private final JdbcTemplate jdbc; public CustomerServiceTicketRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}
 public boolean hasPermission(String userId,String code){Integer value=jdbc.queryForObject("SELECT COUNT(*) FROM user_role ur JOIN role_permission rp ON rp.role_id=ur.role_id JOIN sys_permission p ON p.permission_id=rp.permission_id AND p.enabled=1 WHERE ur.user_id=? AND p.permission_code=?",Integer.class,userId,code);return value!=null&&value>0;}
 public List<CustomerServiceTicketDtos.TicketItem> list(String status,String priority,String keyword,int limit,int offset){StringBuilder w=new StringBuilder(" WHERE 1=1");List<Object>a=new ArrayList<>();if(status!=null&&!status.isBlank()){w.append(" AND t.ticket_status=?");a.add(status);}if(priority!=null&&!priority.isBlank()){w.append(" AND t.priority=?");a.add(priority);}if(keyword!=null&&!keyword.isBlank()){w.append(" AND (t.description LIKE ? OR e.elder_name LIKE ?)");a.add("%"+keyword+"%");a.add("%"+keyword+"%");}a.add(limit);a.add(offset);return jdbc.query("SELECT t.ticket_id,t.assistance_ticket_id,t.elder_id,e.elder_name,u.display_name,t.category,t.priority,t.ticket_status,t.description,t.source_type,t.created_at FROM customer_service_ticket t JOIN elder_profile e ON e.elder_id=t.elder_id LEFT JOIN sys_user u ON u.user_id=t.requester_id"+w+" ORDER BY FIELD(t.priority,'URGENT','NORMAL'),t.created_at DESC LIMIT ? OFFSET ?",(r,n)->new CustomerServiceTicketDtos.TicketItem(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10),r.getString(11)),a.toArray());}
 public long count(String status,String priority,String keyword){return jdbc.queryForObject("SELECT COUNT(*) FROM customer_service_ticket t JOIN elder_profile e ON e.elder_id=t.elder_id WHERE (? IS NULL OR t.ticket_status=?) AND (? IS NULL OR t.priority=?) AND (? IS NULL OR t.description LIKE ? OR e.elder_name LIKE ?)",Long.class,status,status,priority,priority,keyword,keyword,keyword);}
 public Optional<CustomerServiceTicketDtos.TicketItem> find(String id){return listOne("SELECT t.ticket_id,t.assistance_ticket_id,t.elder_id,e.elder_name,u.display_name,t.category,t.priority,t.ticket_status,t.description,t.source_type,t.created_at FROM customer_service_ticket t JOIN elder_profile e ON e.elder_id=t.elder_id LEFT JOIN sys_user u ON u.user_id=t.requester_id WHERE t.ticket_id=?",id);}
 private Optional<CustomerServiceTicketDtos.TicketItem> listOne(String sql,Object...args){return jdbc.query(sql,(r,n)->new CustomerServiceTicketDtos.TicketItem(r.getString(1),r.getString(2),r.getString(3),r.getString(4),r.getString(5),r.getString(6),r.getString(7),r.getString(8),r.getString(9),r.getString(10),r.getString(11)),args).stream().findFirst();}
 public List<CustomerServiceTicketDtos.TicketMessageItem> messages(String id){return jdbc.query("SELECT message_id,sender_role,content,created_at FROM ticket_message WHERE ticket_id=? ORDER BY created_at",(r,n)->new CustomerServiceTicketDtos.TicketMessageItem(r.getString(1),r.getString(2),r.getString(3),r.getString(4)),id);}
 public void status(String id,String target){jdbc.update("UPDATE customer_service_ticket SET ticket_status=?,resolved_at=CASE WHEN ?='RESOLVED' THEN CURRENT_TIMESTAMP ELSE resolved_at END,closed_at=CASE WHEN ?='CLOSED' THEN CURRENT_TIMESTAMP ELSE closed_at END,updated_at=CURRENT_TIMESTAMP WHERE ticket_id=?",target,target,target,id);}
 public String message(String id,String sender,String role,String type,String content){String messageId="tm_"+UUID.randomUUID().toString().replace("-","").substring(0,24);jdbc.update("INSERT INTO ticket_message(message_id,ticket_id,sender_id,sender_role,message_type,content) VALUES (?,?,?,?,?,?)",messageId,id,sender,role,type,content);return messageId;}
 public void mirrorCustomerServiceMessageToAiSession(String ticketId,String content){String messageId="ai_cs_"+UUID.randomUUID().toString().replace("-","").substring(0,24);String trace="trace_cs_"+UUID.randomUUID().toString().replace("-","");String summary=content.length()>500?content.substring(0,500):content;jdbc.update("INSERT INTO ai_assistant_message(message_id,session_id,sender_role,message_type,content_summary,content_text,safety_flag,trace_id) SELECT ?,a.session_id,'SYSTEM','SYSTEM',?,?,0,? FROM customer_service_ticket t JOIN assistance_ticket a ON a.assistance_ticket_id=t.assistance_ticket_id WHERE t.ticket_id=? AND a.session_id IS NOT NULL",messageId,summary,content,trace,ticketId);jdbc.update("UPDATE ai_assistant_session s JOIN assistance_ticket a ON a.session_id=s.session_id JOIN customer_service_ticket t ON t.assistance_ticket_id=a.assistance_ticket_id SET s.updated_at=CURRENT_TIMESTAMP WHERE t.ticket_id=?",ticketId);}
}
