package com.csu.carenest.careadmin.customer;
import com.csu.carenest.careadmin.auth.*; import com.csu.carenest.careadmin.common.ApiException; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.util.*;
@Service public class CustomerServiceTicketService {private final AuthService auth;private final CustomerServiceTicketRepository repo;public CustomerServiceTicketService(AuthService a,CustomerServiceTicketRepository r){auth=a;repo=r;}
 public CustomerServiceTicketDtos.PageResult<CustomerServiceTicketDtos.TicketItem> list(String token,String st,String pr,String kw,int page,int size){CurrentUser u=access(token);if(page<1||size<1||size>50)throw new ApiException(422,"invalid page");return new CustomerServiceTicketDtos.PageResult<>(repo.list(st,pr,kw,size,(page-1)*size),repo.count(st,pr,kw),page,size);}
 public CustomerServiceTicketDtos.TicketDetail detail(String token,String id){access(token);return repo.find(id).map(t->new CustomerServiceTicketDtos.TicketDetail(t,repo.messages(id))).orElseThrow(()->new ApiException(404,"ticket not found"));}
 @Transactional public CustomerServiceTicketDtos.TicketItem status(String token,String id,CustomerServiceTicketDtos.StatusRequest req){CurrentUser u=access(token);var t=repo.find(id).orElseThrow(()->new ApiException(404,"ticket not found"));if(req==null||req.targetStatus()==null||!allowed(t.ticketStatus(),req.targetStatus()))throw new ApiException(409,"invalid ticket transition");if("URGENT".equals(t.priority())&&Set.of("RESOLVED","CLOSED").contains(req.targetStatus())&&!repo.hasFollowUp(id))throw new ApiException(409,"urgent ticket requires follow-up before completion");repo.status(id,req.targetStatus());repo.message(id,u.userId(),u.primaryRole(),"SYSTEM",req.handleResult()==null?req.targetStatus():req.handleResult());return repo.find(id).orElseThrow();}
 @Transactional public CustomerServiceTicketDtos.TicketMessageItem message(String token,String id,CustomerServiceTicketDtos.MessageRequest req){CurrentUser u=access(token);if(repo.find(id).isEmpty())throw new ApiException(404,"ticket not found");if(req==null||req.content()==null||req.content().isBlank())throw new ApiException(422,"content is required");String mid=repo.message(id,u.userId(),u.primaryRole(),"TEXT",req.content());return new CustomerServiceTicketDtos.TicketMessageItem(mid,u.primaryRole(),req.content(),java.time.LocalDateTime.now().toString());}
 private CurrentUser access(String token){CurrentUser user=auth.requireAnyRole(token,RoleCode.ADMIN,RoleCode.CUSTOMER_SERVICE);if(!repo.hasPermission(user.userId(),"CUSTOMER_SERVICE_TICKET_HANDLE"))throw new ApiException(403,"forbidden");return user;}
 private boolean allowed(String from,String to){return from.equals("PENDING")&&to.equals("PROCESSING")||from.equals("PROCESSING")&&(to.equals("RESOLVED")||to.equals("CLOSED"));}}
